gui:
  nerdFontsVersion: 3
  theme:
    selectedLineBgColor:
      - "#292e42"
git:
  pagers:
    - pager: delta --dark --paging=never
  autoFetch: false
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --oneline
  allBranchesLogCmds:
    - git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline
  parseEmoji: true
  log:
    showWholeGraph: false
update:
  days: 28
disableStartupPopups: true
